#!/bin/bash

### Git pre-commit hook used as C++ linter

# Check that cpplint is installed
which cpplint &> /dev/null
if [[ "$?" == 1 ]]; then
    echo "Please install cpplint"
    exit 1
fi

## Actually run cpplint

# Get all files to check
files=($(find src/ -name '*.?pp' | grep --invert-match "src/libs/*"))

# Run cpplint
if ! cpplint ${files}; then
    echo
    echo "cpplint did not pass!"
    echo

    exit 1
fi
