#!/bin/bash

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ ${protected_branch} = ${current_branch} ]; then
    echo
    echo "DO NOT PUSH STRAIGHT TO MASTER!"
    echo
    exit 1
fi
